### ISSUE TITLE
Lag in game + cascading worldgen lag?

### ISSUE THREAD

**Issue by spiderkitten** [CaiganMythFang/FurcraftianTailIssues#2]
Hi, I am getting a lot of lag and a message repeatedly appearing in my game output :  

"Can't keep up! Did the system time change, or is the server overloaded? Running 6788ms behind, skipping 135 tick(s)"  

When I first started the world I got it right from the start. The game would freeze every few seconds and my log was filled with that message. So I changed some of the graphic settings and increased my memory in the Twitch Client settings from 6 to about 8GB and it went away and I was able to play for a while, but then it started happening again. I increased my memory to around 10GB and it was fine again for a while, but then after an hour I get the lag and message again. 

Not sure if it is related, but I get a lot of messages like this too:  

"[12:20:13] [Server thread/WARN] [FML]: The Lost Cities loaded a new chunk [10, -53] in dimension 0 (overworld) while populating chunk [11, -53], causing cascading worldgen lag.
[12:20:13] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config." 

"[12:20:27] [Server thread/WARN] [FML]: MrTJPCore loaded a new chunk [10, -55] in dimension 0 (overworld) while populating chunk [10, -54], causing cascading worldgen lag.
[12:20:27] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config."  

"[12:21:36] [Server thread/WARN] [FML]: Recurrent Complex loaded a new chunk [6, -49] in dimension 0 (overworld) while populating chunk [7, -50], causing cascading worldgen lag.
[12:21:36] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config."

And the same message for other mods like Doomlike Dungeons and Electroblob's Wizardry too. 

Should I be reporting this to the mod authors?  or is there anything I can do to fix this?  I can allocate more memory but I feel like the issue would just present itself again. Not sure what else to try. This seems to be the only mod pack I've played recently that has this issue. 

A Furcraftian Tale Ver 1.3.0
No extra mods added.

**Comment by CaiganMythFang** [comment]
Drop down to around 7 gigs max, and try the following java arguments in your Twitch > Preferences > Minecraft > Additional Java Arguments  : 

-d64 -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:MaxGCPauseMillis=50 -XX:+UseStringDeduplication -XX:+UseCompressedOops -XX:+UseCodeCacheFlushing -XX:ParallelGCThreads=4 -Dfml.ignoreInvalidMinecraftCertificates=true -Dfml.ignorePatchDiscrepancies=true

**Comment by spiderkitten** [comment]
Thanks, I will give that a go.
