### ISSUE TITLE
Modpack does not start

### ISSUE THREAD

**Issue by Garik1502** [CaiganMythFang/FurcraftianTailIssues#3]
Crash log: 
`Minecraft folder is:
instances/A Furcraftian Tail - FOGCraft Goes West/minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/java.exe

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1024m, -Xmx2048m, -Duser.language=en, -jar, D:/Games/MultiMC/jars/NewLaunch.jar]

Minecraft process ID: 236

Using onesix launcher.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  D:/Games/MultiMC/instances/A Furcraftian Tail - FOGCraft Goes West/natives

Traits:
  []

Libraries:
  D:/Games/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  D:/Games/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  D:/Games/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  D:/Games/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  D:/Games/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  D:/Games/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  D:/Games/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  D:/Games/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  D:/Games/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  D:/Games/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  D:/Games/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  D:/Games/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  D:/Games/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  D:/Games/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  D:/Games/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  D:/Games/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  D:/Games/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  D:/Games/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  D:/Games/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  D:/Games/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  D:/Games/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  D:/Games/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  D:/Games/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  D:/Games/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  D:/Games/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  D:/Games/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  D:/Games/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  D:/Games/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  D:/Games/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  D:/Games/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
  D:/Games/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
  D:/Games/MultiMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  D:/Games/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  D:/Games/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  D:/Games/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  D:/Games/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  D:/Games/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  D:/Games/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  D:/Games/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  D:/Games/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  D:/Games/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  D:/Games/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  D:/Games/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  D:/Games/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  D:/Games/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  D:/Games/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  D:/Games/MultiMC/libraries/jline/jline/2.13/jline-2.13.jar (missing)
  D:/Games/MultiMC/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  D:/Games/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  D:/Games/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.4.2705/forge-1.12.2-14.23.4.2705-universal.jar (missing)
  D:/Games/MultiMC/versions/1.12.2/1.12.2.jar

Mods:
  ActuallyAdditions-1.12.2-r135
  ActuallyBaubles-1.12-1.1
  actuallycomputers-2.1.0
  AdHooks-1.12.2-3.1.3.0-build.0121
  Animalium-0.3.7
  animania-1.12.2-1.4.8
  Aroma1997Core-1.12.2-2.0.0.0.b155
  Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37
  autooredictconv-1.12-1.0
  AutoRegLib-1.3-18
  Avaritia-1.12-3.2.0.13-universal
  AvaritiaTweaks-1.12.2-1.1
  base-1.12.2-3.9.0
  Baubles-1.12-1.5.2
  BetterQuesting-3.5.259
  questbook-3.1.1-1.12
  BiblioCraft[v2.4.4][MC1.12.2]
  blockdrops-1.12.2-1.4.0
  BlockDropsTweaker-1.12.2-2.4
  bonsaitrees-1.0.5-b77
  Bookshelf-1.12.2-2.3.552
  Botania r1.10-354
  BrandonsCore-1.12-2.4.2.157-universal
  buildersguides-1.12.2-1.0.1
  Capsule-1.12.2-3.1.69
  Chameleon-1.12-4.1.3
  Chargers-1.12.2-1.0.0.1
  Chisel-MC1.12.2-0.2.0.31
  chiselsandbits-14.18
  chococraft_1.12.1-0.9.1.52
  Chunk Pregenerator V1.12-1.8.1
  CodeChickenLib-1.12.2-3.1.9.344-universal
  CoFHCore-1.12.2-4.5.2.19-universal
  CoFHWorld-1.12.2-1.2.0.5-universal
  ContentTweaker-1.12.2-4.6.0
  Controlling-3.0.6
  CookingForBlockheads_1.12.2-6.4.40
  CosmeticArmorReworked-1.12.2-v1
  CraftStudio-1.0.0.93-mc1.12-alpha
  CraftTweaker2-1.12-4.1.8
  CreativeCore_v1.9.22_mc1.12.2
  CTM-MC1.12-0.3.0.15
  CustomMainMenu-MC1.12.2-2.0.8
  CustomNPCs_1.12.2(13may18)
  CustomStartingGear-1.12-1.2.0.9-universal
  Cyclic-1.12.2-1.15.12
  D3Core-1.12.2-1.3.2.71
  Decocraft-2.6.0_1.12.2
  deepresonance-1.12-1.7.0
  DefaultOptions_1.12.2-9.2.7
  DefaultWorldGenerator-port-1.12-2.3
  DoomlikeDungeons-1.11.1-MC1.12.2
  Draconic-Evolution-1.12-2.3.11.290-universal
  ElecCore-1.12.2-1.8.434
  Electroblob's Wizardry - 4.1.2 - MC 1.12.2
  ElevatorMod-1.12.2-1.3.6
  EmberRootZoo-1.12-1.3.7
  embers-0.230
  Enchiridion-1.12.2-3.3.3
  environmentaltech-1.12.2-2.0.11a
  ExCompressum_1.12.2-3.0.22
  PTRLib-1.0.2
  ExtraRails-1.12-1.3.0
  foamfix-0.9.9.1-1.12.2-anarchy
  ForgeEndertech-1.12.2-4.3.10.0-build.0125
  ForgeMultipart-1.12.2-2.4.2.60-universal
  FTBUtilities-5.1.0.27
  FTBLib-5.1.0.22
  GameStages-1.12.2-2.0.91
  HuntingDimension-1.12.2-1.0.24
  hydrophobia-1.12 - 1.0.1c
  ImmersiveEngineering-0.12-82
  Immersive HempCraft-1.12-0.0.6.2
  ImmersiveRailroading-1.2.1_1.12
  incontrol-1.12-3.8.0
  industrialforegoing-1.12.2-1.10.1-176
  inventorypets-1.12-1.5
  InventoryTweaks-1.63
  IronBackpacks-1.12.2-3.0.8-12
  ironchest-1.12.2-7.0.44.829
  ItemStages-1.12.2-2.0.35
  IvToolkit-1.3.3-1.12
  JEHC-1.12.2-1.5.1.0
  jeiintegration_1.12.2-1.5.1.36
  jeivillagers-1.12-1.0.2
  journeymap-1.12.2-5.5.2
  JsonLootBags-1.12.2-1.0.0.15
  jei_1.12.2-4.10.0.199
  JustEnoughResources-1.12.2-0.8.6.28
  LagGoggles-FORGE-1.12.2-4.1
  LootBags-1.12.2-2.5.6
  LootTweaker-1.12.2-0.0.7
  lostsouls-1.12-1.1.4
  Mantle-1.12-1.3.2.24
  mdecore-1.12-1.0
  mcjtylib-1.12-3.0.1
  meecreeps-1.12-1.2.0
  MineTweakerRecipeMaker-1.12.2-1.2.2.30
  miniheads-1.0.7a-1.12
  MmmMmmMmmMmm-1.12-1.14
  [1.12]MoVillages-1.5.4
  EconomyInc-1.5MC1.12.2
  modnametooltip_1.12.2-1.10.0
  Modular Diversity-0.2hotfix
  modularmachinery-1.9.4
  MoreLootStuff-1.12.2-0.0.4
  moreoverlays-1.13-mc1.12.1
  MouseTweaks-2.8-mc1.12.1
  furniture-4.2.0-1.12.2
  guns-0.3.1-1.12.2
  cjcm-1.0
  MrTJPCore-1.12.2-2.1.3.35-universal
  multishot-1.12.0-3.3.0
  NetherPortalFix_1.12.1-5.3.13
  NoMoreRecipeConflict-0.10(1.12.2)
  NotEnoughItems-1.12.2-2.4.1.233-universal
  notenoughroofs-1.12.2-0.8.0.0
  notenoughwands-1.12-1.7.0
  obfuscate-0.2.4-1.12.2
  omlib-1.12.2-3.0.0-148
  OnlinePicFrame_v1.4.18_mc1.12.2
  openmodularturrets-1.12.2-3.0.1-257
  OpenComputers-MC1.12.2-1.7.2.67
  OpenPrinter-1.12.2-0.1.0.2
  OreStages-1.12.2-2.0.30
  Pam's HarvestCraft 1.12.2u
  plustic-6.5.2.0
  ProjectRed-1.12.2-4.9.1.92-Base
  ProjectRed-1.12.2-4.9.1.92-mechanical
  ProjectRed-1.12.2-4.9.1.92-world
  ProjectRed-1.12.2-4.9.1.92-fabrication
  ProjectRed-1.12.2-4.9.1.92-lighting
  ProjectRed-1.12.2-4.9.1.92-integration
  Psi-r1.1-59
  Quark-r1.4-125
  QuickLeafDecay-MC1.12.1-1.2.4
  RainbowOaks-1.12-1.0.4
  RebornCore-1.12.2-3.8.9.300-universal
  RebornStorage-1.12.2-3.1.0.50
  RecipeStages-1.1.1
  RecurrentComplex-1.4.7
  recycler-2.0.0-1.12
  RedstoneFlux-1.12-2.0.2.3-universal
  refinedstorage-1.5.34
  refinedstorageaddons-0.3
  ResourceLoader-MC1.12.1-1.5.3
  rftools-1.12-7.53
  rftoolsctrl-1.12-1.9.0
  rftoolspower-1.12-1.1.0
  Scannable-MC1.12-1.6.3.19
  Scavenge V1.12-1.8.2
  Forgelin-1.7.4
  ShadowMC-1.12-3.8.0
  SilentLib-1.12.2-2.3.2-109
  SilentsGems-1.12.2-2.7.2b-270
  SGExtraParts-1.12-1.4.1-34
  SlashBlade-mc1.12-r13
  StandardExpansion-3.4.143
  statues-1.12.X-0.8.6.3
  StevesCarts-1.12.2-2.4.21.105
  StorageDrawers-1.12.2-5.3.6
  tacotuesday-1.12.2-2.0.13
  Tails-1.12-1.10.0
  tesla-core-lib-1.12.2-1.0.14
  tetra-1.12.2-0.8.1
  lostcities-1.12-2.0.7
  theoneprobe-1.12-1.4.23
  TConstruct-1.12.2-2.10.1.87
  tinkersoc-0.4
  tombstone-2.9.7-1.12
  topaddons-1.12.2-1.7.0
  torchmaster_1.12.2-1.6.4.62
  TrackAPI-1.1_1.12
  Traverse-1.12.2-1.5.4-61
  TreeChopper-1.12.2-1.2.4
  trumpetskeleton-1.12-1.0.2.1
  valkyrielib-1.12.2-2.0.11a
  VanillaFix-1.0.9-97
  VariedCommodities_1.12.2(15may18
  ViesCraft-1.12.2-5.9.13
  VillagerTrades-1.12-0.6.4
  WaterStrainer-1.12-3.2.0
  xnet-1.12-1.7.1
  Xtones-1.12-1.0.8-11
  yoyos_1.12.2-1.2.2.20

Params:
  [--username, <PROFILE NAME>, --version, MultiMC5, --gameDir, D:/Games/MultiMC/instances/A Furcraftian Tail - FOGCraft Goes West/minecraft, --assetsDir, D:/Games/MultiMC/assets, --assetIndex, 1.12, --uuid, <PROFILE ID>, --accessToken, <ACCESS TOKEN>, --userType, mojang, --versionType, Forge, --tweakClass, net.minecraftforge.fml.common.launcher.FMLTweaker]

Window size: 854 x 480

Preparing native libraries...
Extracting text2speech-1.10.3-natives-windows.jar
Extracting jinput-platform-2.0.5-natives-windows.jar
Extracting lwjgl-platform-2.9.1-natives-windows.jar

[18:33:51] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[18:33:51] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraftforge.fml.common.launcher.FMLTweaker
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_171]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_171]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Процесс завершился с кодом 1.
`

**Comment by CaiganMythFang** [comment]
It looks like you are trying to launch with 2 gigs of ram max allocated.
You'll want to up that to around 5 or 6 gigs instead.

**Comment by Garik1502** [comment]
Thank! But here now the new crash: https://paste.dimdev.org/nejubumele.mccrash

**Comment by CaiganMythFang** [comment]
What video card do you have? And is it updated to the latest drivers?

**Comment by Garik1502** [comment]
Zotac GTX 650 
Drivers: 398.82

**Comment by Garik1502** [comment]
Updated drivers, did not help.

**Comment by CaiganMythFang** [comment]
Looking into it a bit more, try these two things 

1) Make sure MultiMC is up to date.
2) Update CodeChickenLib, which might fix the issue as well

**Comment by CaiganMythFang** [comment]
I am closing this issue for now, since a new update has recently be released. If you ares still having issues, please open a new Issue with updated details.
Thank you!
